services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - app_network

  postgres:
    image: postgres:latest
    container_name: curso_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: WSKEXPXdhNWOekZ
      POSTGRES_DB: curso_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: curso_postgres_data

networks:
  app_network: